### ISSUE TITLE
nc48ads_a100_v4 wrong configuration file with AlmaLinux 8.7

### ISSUE THREAD

**Issue by xpillons** [Azure/azurehpc-health-checks#71]
The check_hw_cpuinfo test is configured with 1 socket in the nc48ads_a100_v4.conf file

`check_hw_cpuinfo 1 48 48`

While this works on Ubuntu 20.04, it failed on AlmaLinux 8.7 as the OS reports 2 sockets

**Comment by rafsalas19** [comment]
will look into this

**Comment by rafsalas19** [comment]
@xpillons, I am unable to repro this condition. I think this may be a platform issue rather than AzNHC. If you can keep all the meta data from your VM. We may need to submit a ticket to HPCPlatform.

However, first lets verify that the OS tools show the same behavior.
Does lscpu or /proc/info show the same behavior?

**Comment by xpillons** [comment]
@rafsalas19 actually it was a bad node !!! so the configuration is correct, just me being unlucky, and I don't have kept the node metadata
